#ifndef __INPUTS_CONFIG_H__
#define __INPUTS_CONFIG_H__

#define HOLONOM_JOYSTICK_X_AXIS_ZONE_MIN 0
#define HOLONOM_JOYSTICK_X_AXIS_ZONE_MAX 1024

#define JOYSTICK_X_AXIS_ZONE_MIN 475
#define JOYSTICK_X_AXIS_ZONE_MAX 549

#define HOLONOM_JOYSTICK_Y_AXIS_ZONE_MIN 0
#define HOLONOM_JOYSTICK_Y_AXIS_ZONE_MAX 1024

#endif