#ifndef __INPUTS_CONFIG_H__
#define __INPUTS_CONFIG_H__

#define JOYSTICK_X_AXIS_PIN A0
#define JOYSTICK_Y_AXIS_PIN A1
#define HOLONOM_JOYSTICK_X_AXIS_PIN A3
#define HOLONOM_JOYSTICK_Y_AXIS_PIN A4

#define GRABBER_HEIGHT_POTENTIOMETER A5
#define GRABBER_OPENING_POTENTIOMETER A6

#define SOLAR_PANEL_ROD_BUTTON 99
#define MAGNETS_BUTTON 99
#define LEFT_PUSHER_BUTTON 22
#define RIGH_PUSHER_BUTTON 23

#endif